#!/bin/bash

colorizer() {
    color=$1
    color_code="0"
    
    if [ $color = "black" ]; then
        color_code="0"
    elif [ $color = "red" ]; then
        color_code="1"
    elif [ $color = "yellow"]; then
        color_code="2"
    elif [ $color = "green"]; then
        color_code="2"
    elif [ $color = "yellow"]; then
        color_code="3"
    elif [ $color = "blue"]; then
        color_code="4"
    elif [ $color = "magenta"]; then
        color_code="5"
    elif [ $color = "cyan"]; then
        color_code="6"
    elif [ $color = "white"]; then
        color_code="7"
    fi

    printf "\e[3%sm$2\e[m" $color_code
}

# colorizer "red" "hello there"
colorizer $1 $2